version: '3.8'

services:
  # MySQL Database
  mysql:
    image: mysql:8.0
    container_name: portfolio_mysql_dev
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: portfolio_db
      MYSQL_USER: portfolio_user
      MYSQL_PASSWORD: portfolio_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_dev_data:/var/lib/mysql
      - ./mysql-init:/docker-entrypoint-initdb.d
    networks:
      - portfolio_dev_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  # Flask Application
  web:
    build: .
    container_name: portfolio_web_dev
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
      - DB_HOST=mysql
      - DB_USER=portfolio_user
      - DB_PASSWORD=portfolio_password
      - DB_NAME=portfolio_db
      - SECRET_KEY=dev-secret-key-change-in-production
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - portfolio_dev_network
    volumes:
      - ./logs:/app/logs
      - .:/app  # Mount source code for development
    command: python app.py

volumes:
  mysql_dev_data:
    driver: local

networks:
  portfolio_dev_network:
    driver: bridge